<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Authors>Asad Sohail</Authors>
    <Version>0.1.0</Version>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
</Project>
